version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:15"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:30"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
